<section class="related_wrap">
  <h4 class="section_title related_wrap_title">Related Posts</h4>
  <div class="columns_wrap posts_container columns_padding_bottom">
    <div class="column-1_2"><div id="post-55"
class="related_item related_item_style_2 post_format_standard post-55 post type-post status-publish format-standard has-post-thumbnail hentry category-do-it-yourself category-tutorials tag-gifts tag-happybirthday tag-popular tag-present tag-trend"><div class="post_featured with_thumb hover_icon"><img width="406" height="271" src="http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10.jpg" class="attachment-heartstar-thumb-large size-heartstar-thumb-large wp-post-image" alt="" srcset="http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10.jpg 2400w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-760x507.jpg 760w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-370x247.jpg 370w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-300x200.jpg 300w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-768x512.jpg 768w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-1024x683.jpg 1024w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-10-600x400.jpg 600w" sizes="(max-width: 406px) 100vw, 406px" /><div class="mask"></div><div class="icons"><a href="http://heartstar.axiomthemes.com/2017/09/29/30-gifts-your-dad-will-totally-love/" aria-hidden="true" class="icon-017-view"></a></div></div><div class="post_header entry-header">		<h6 class="post_title entry-title"><a href="http://heartstar.axiomthemes.com/2017/09/29/30-gifts-your-dad-will-totally-love/">30 Gifts Your Dad Will Totally Love</a></h6>
</div>
</div></div><div class="column-1_2"><div id="post-87"
class="related_item related_item_style_2 post_format_video post-87 post type-post status-publish format-video has-post-thumbnail hentry category-do-it-yourself tag-happybirthday tag-jewellery post_format-post-format-video"><div class="post_featured with_thumb hover_play"><img width="406" height="271" src="http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2.jpg" class="attachment-heartstar-thumb-large size-heartstar-thumb-large wp-post-image" alt="" srcset="http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2.jpg 2400w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-760x507.jpg 760w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-370x247.jpg 370w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-300x200.jpg 300w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-768x512.jpg 768w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-1024x683.jpg 1024w, http://heartstar.axiomthemes.com/wp-content/uploads/2017/09/image-2-600x400.jpg 600w" sizes="(max-width: 406px) 100vw, 406px" /><div class="mask"></div><div class="post_video_hover" data-video="&lt;iframe src=&quot;https://player.vimeo.com/video/110962054?autoplay=1&quot; width=&quot;640&quot; height=&quot;360&quot;    allowfullscreen&gt;&lt;/iframe&gt;"></div><div class="post_video video_frame"></div></div><div class="post_header entry-header">		<h6 class="post_title entry-title"><a href="http://heartstar.axiomthemes.com/2017/09/29/birthday-christmas-gifts-guidelines/">Birthday &#038; Christmas Gifts Guidelines</a></h6>
</div>
</div></div>				</div>
</section>
